### ISSUE TITLE
Slow navigation between menus

### ISSUE THREAD

**Issue by thatguy530** [fantabulous-tech/solo-adventurers-toolbox#2]
First of all, let me just say props for the great work, this tool is wonderful.
My only issue with it is that it takes very long for each menu to load due to the fade-in animation (about 2 seconds but with multiple submenus it quickly stacks up).
Perhaps a theme option could be included to turn off that animation and just give us the raw HTML buttons. Seeing the speed go to would be a godsend.

**Comment by fantabulous-tech** [comment]
I was finally able to fix this one! The fade in is much faster now.
