### ISSUE TITLE
Unsupported Level 4 with Party Size 1

### ISSUE THREAD

**Issue by hotshotberad** [fantabulous-tech/solo-adventurers-toolbox#3]
When party size is set to 1, and level to 4, treasure hoard and some other scripts generate the error "!!! Unsupported level: 4 with party of 1. !!!

**Comment by fantabulous-tech** [comment]
Thanks for reporting the issue!

Loot and hoards are based on creating encounters for the party and unfortunately only parties of 1 at level 1, 2, and 3 or parties of 2 at level 1 or 2 are supported. I've updated the error messages to better report these current limits.
